/* Home Gym Coach — exercise library + programs
   Equipment: bench, DB 2–32kg, pull-up bar, bands, ball, treadmill (flat)
*/
window.HGC_DATA = {
  dbSteps: [2, 4, 8, 12, 16, 20, 24, 28, 32],

  exercises: {
    incline_db_press: {
      id: "incline_db_press",
      name: "Incline DB Press",
      nameTh: "ดัมเบลกดอกบนม้านั่งเอียง",
      muscle: "อกบน · ไหล่หน้า",
      equipment: "ม้านั่ง + ดัมเบล",
      image: "assets/exercises/press.jpg",
      cues: [
        "หลังและศีรษะติดม้านั่ง เท้าแตะพื้นมั่นคง",
        "ดัมเบลลดช้า ๆ จนข้อศอกลึกกว่าอกเล็กน้อย",
        "กดขึ้นโดยไม่ล็อกข้อศอกแรงเกินไป ควบคุมตลอด",
      ],
      defaultSets: 4,
      defaultReps: "8-15",
      startKg: 16,
      restSec: 90,
    },
    flat_db_press: {
      id: "flat_db_press",
      name: "Flat DB Press",
      nameTh: "ดัมเบลกดอกม้านั่งราบ",
      muscle: "อก · ไตรเซป",
      equipment: "ม้านั่ง + ดัมเบล",
      image: "assets/exercises/press.jpg",
      cues: [
        "สะบักกดลง-เข้าหากันเล็กน้อย อกเปิด",
        "ข้อมือตรงเหนือข้อศอกตอนกดขึ้น",
        "อย่าโก่งหลังมากเกิน — ก้นติดม้านั่ง",
      ],
      defaultSets: 3,
      defaultReps: "8-15",
      startKg: 16,
      restSec: 90,
    },
    db_ohp: {
      id: "db_ohp",
      name: "DB Overhead Press",
      nameTh: "ดัมเบลยกเหนือศีรษะ",
      muscle: "ไหล่ · แกนกลาง",
      equipment: "ดัมเบล (ยืนหรือนั่ง)",
      image: "assets/exercises/ohp.jpg",
      cues: [
        "ลำตัวตรง เกร็งแกนกลาง อย่าแอ่นหลังมาก",
        "กดขึ้นจนแขนเกือบตรง แล้วลดช้า ๆ ถึงระดับคาง–หู",
        "หายใจออกตอนกดขึ้น",
      ],
      defaultSets: 3,
      defaultReps: "8-15",
      startKg: 8,
      restSec: 90,
    },
    lateral_raise: {
      id: "lateral_raise",
      name: "DB Lateral Raise",
      nameTh: "ยกด้านข้างสร้างไหล่กว้าง",
      muscle: "ไหล่ด้านข้าง (V-taper)",
      equipment: "ดัมเบลเบา",
      image: "assets/exercises/lateral.jpg",
      cues: [
        "ข้อศอกเล็กน้อยงอ นึกว่าเทน้ำออกจากเหยือกเล็กน้อย",
        "ยกถึงประมาณไหล่ — ไม่เหวี่ยงตัว",
        "ลดช้า 2–3 วินาที เน้นควบคุม",
      ],
      defaultSets: 3,
      defaultReps: "12-20",
      startKg: 4,
      restSec: 60,
    },
    db_kickback: {
      id: "db_kickback",
      name: "DB Tricep Kickback",
      nameTh: "ไตรเซปเหวี่ยงหลัง",
      muscle: "ไตรเซป",
      equipment: "ดัมเบล",
      image: "assets/exercises/arms.jpg",
      cues: [
        "หลังตรงเกือบขนานพื้น ข้อศอกติดลำตัว",
        "เหยียดแขนหลังสุดแล้วบีบไตร 1 วินาที",
        "อย่าเหวี่ยงไหล่ — ขยับแค่ข้อศอกลงไป",
      ],
      defaultSets: 3,
      defaultReps: "12-20",
      startKg: 4,
      restSec: 60,
    },
    band_pushdown: {
      id: "band_pushdown",
      name: "Band Tricep Pushdown",
      nameTh: "ยางกดไตรเซปลง",
      muscle: "ไตรเซป",
      equipment: "ยางยืด (ติดสูงหรือยันประตู)",
      image: "assets/exercises/band.jpg",
      cues: [
        "ข้อศอกติดข้างลำตัว กดลงจนแขนเหยียด",
        "กลับขึ้นช้า ๆ อย่าให้ข้อศอกพุ่งไปข้างหน้า",
        "เกร็งแกนกลาง ลำตัวนิ่ง",
      ],
      defaultSets: 3,
      defaultReps: "12-20",
      startKg: null,
      bandLevel: "กลาง",
      restSec: 60,
    },
    pullup: {
      id: "pullup",
      name: "Pull-Up",
      nameTh: "โหนบาร์ดึงตัวขึ้น",
      muscle: "หลังกว้าง · ไบเซป",
      equipment: "บาร์โหน",
      image: "assets/exercises/pullup.jpg",
      cues: [
        "มือกว้างกว่าไหล่เล็กน้อย หลังเหยียดตอนเริ่ม",
        "ดึงอกเข้าหาบาร์ ไม่เหวี่ยงสะโพก",
        "ลดลงช้าจนแขนเกือบตรง — เป้าตอนนี้ 3–4 ครั้งสวย ๆ",
      ],
      defaultSets: 3,
      defaultReps: "3-8",
      startKg: null,
      restSec: 120,
      note: "ระดับปัจจุบันประมาณ 3–4 ครั้ง × 3 เซ็ต — คุณภาพสำคัญกว่าจำนวน",
    },
    band_assisted_pullup: {
      id: "band_assisted_pullup",
      name: "Band-Assisted Pull-Up",
      nameTh: "โหนช่วยด้วยยาง (volume เพิ่ม)",
      muscle: "หลัง · ไบเซป",
      equipment: "บาร์โหน + ยาง",
      image: "assets/exercises/pullup.jpg",
      cues: [
        "ร้อยยางที่บาร์แล้วคุกเข่าหรือยืนบนห่วงยาง",
        "ดึงแบบเดียวกับ Pull-Up — อกเข้าหาบาร์",
        "ใช้ชุดนี้เพิ่ม volume หลังทำ Pull-Up หลักแล้ว",
      ],
      defaultSets: 2,
      defaultReps: "6-12",
      startKg: null,
      bandLevel: "ช่วยปานกลาง",
      restSec: 90,
    },
    db_row: {
      id: "db_row",
      name: "Single-Arm DB Row",
      nameTh: "ดัมเบลดึงหลังข้างเดียว",
      muscle: "หลังกลาง · ไหล่หลัง",
      equipment: "ม้านั่ง + ดัมเบล",
      image: "assets/exercises/row.jpg",
      cues: [
        "มือ-เข่าข้างหนึ่งยันม้านั่ง หลังตรงขนานพื้น",
        "ดึงดัมเบลเข้าสะโพก ไม่ยกไหล่ขึ้นหู",
        "บีบสะบักตอนบนสุด แล้วลดช้า",
      ],
      defaultSets: 3,
      defaultReps: "8-15",
      startKg: 16,
      restSec: 75,
    },
    rear_delt_fly: {
      id: "rear_delt_fly",
      name: "DB Rear Delt Fly",
      nameTh: "เปิดไหล่หลังด้วยดัมเบล",
      muscle: "ไหล่หลัง · ท่าทาง",
      equipment: "ดัมเบลเบา",
      image: "assets/exercises/rear.jpg",
      cues: [
        "โน้มตัว หลังตรง ยกแขนแยกด้านข้างเหมือนเปิดปีก",
        "น้ำหนักเบา ควบคุม — ไม่เหวี่ยง",
        "นึกบีบสะบักเข้าหากันตอนบน",
      ],
      defaultSets: 3,
      defaultReps: "12-20",
      startKg: 2,
      restSec: 60,
    },
    band_face_pull: {
      id: "band_face_pull",
      name: "Band Face Pull",
      nameTh: "ยางดึงเข้าหน้า (ท่าทาง + ไหล่หลัง)",
      muscle: "ไหล่หลัง · rotator",
      equipment: "ยางยืด",
      image: "assets/exercises/band.jpg",
      cues: [
        "ดึงยางเข้าหาหน้า แยกมือตอนใกล้ใบหน้า",
        "ข้อศอกสูงประมาณไหล่",
        "ช้าและนิ่ง — ท่านี้ช่วยไหล่และท่าทางมาก",
      ],
      defaultSets: 3,
      defaultReps: "12-20",
      startKg: null,
      bandLevel: "เบา–กลาง",
      restSec: 60,
    },
    db_curl: {
      id: "db_curl",
      name: "DB Bicep Curl",
      nameTh: "ดัมเบลงอแขนไบเซป",
      muscle: "ไบเซป",
      equipment: "ดัมเบล",
      image: "assets/exercises/arms.jpg",
      cues: [
        "ข้อศอกติดข้างลำตัว อย่าเหวี่ยงตัว",
        "งอขึ้นสุดแล้วลดช้า 2–3 วินาที",
        "ถ้าเหวี่ยงได้ง่าย ลดน้ำหนักทันที",
      ],
      defaultSets: 3,
      defaultReps: "12-20",
      startKg: 8,
      restSec: 60,
    },
    db_squat: {
      id: "db_squat",
      name: "Goblet / DB Squat",
      nameTh: "สควอทถือดัมเบล",
      muscle: "ขา · ก้น",
      equipment: "ดัมเบล",
      image: "assets/exercises/squat.jpg",
      cues: [
        "เท้ากว้างประมาณไหล่ นิ้วเท้าแยกเล็กน้อย",
        "นั่งสะโพกไปหลัง เข่าตามแนวปลายเท้า",
        "อกยก หลังไม่โก่ง — ลึกเท่าที่ควบคุมได้",
      ],
      defaultSets: 3,
      defaultReps: "8-15",
      startKg: 16,
      restSec: 90,
    },
    db_rdl: {
      id: "db_rdl",
      name: "DB Romanian Deadlift",
      nameTh: "RDL ดัมเบล (หลังขา–ก้น)",
      muscle: "แฮมสตริง · ก้น · หลังล่าง",
      equipment: "ดัมเบล",
      image: "assets/exercises/rdl.jpg",
      cues: [
        "เข่างอเล็กน้อย ดันสะโพกไปหลัง ดัมเบลเลาะขา",
        "หลังตรงตลอด — รู้สึกตึงหลังขา แล้วดันสะโพกกลับ",
        "อย่าโค้งหลังส่วนล่าง",
      ],
      defaultSets: 3,
      defaultReps: "8-15",
      startKg: 16,
      restSec: 90,
    },
    split_squat: {
      id: "split_squat",
      name: "DB Split Squat",
      nameTh: "สควอทแยกขา (ข้างละข้าง)",
      muscle: "ขา · ก้น · ทรงตัว",
      equipment: "ดัมเบล",
      image: "assets/exercises/split.jpg",
      cues: [
        "ก้าวยาว ลดเข่าหลังลงตรง ๆ",
        "น้ำหนักส่วนใหญ่ที่ขาหน้า ลำตัวตั้งตรง",
        "ทำครบข้างหนึ่งก่อนสลับ — นับข้างละเซ็ต",
      ],
      defaultSets: 3,
      defaultReps: "8-15/ข้าง",
      startKg: 8,
      restSec: 75,
    },
    calf_raise: {
      id: "calf_raise",
      name: "DB Calf Raise",
      nameTh: "ยกน่องถือดัมเบล",
      muscle: "น่อง",
      equipment: "ดัมเบล",
      image: "assets/exercises/calf.jpg",
      cues: [
        "ยกส้นสูงสุด หยุด 1 วินาที แล้วลดช้า",
        "อย่าเด้ง — คุมทั้งขึ้นและลง",
      ],
      defaultSets: 3,
      defaultReps: "12-20",
      startKg: 12,
      restSec: 45,
    },
    ball_crunch: {
      id: "ball_crunch",
      name: "Stability Ball Crunch",
      nameTh: "ครันช์บนบอลทรงตัว",
      muscle: "หน้าท้อง",
      equipment: "บอล",
      image: "assets/exercises/core.jpg",
      cues: [
        "หลังพาดบอล เท้ายันพื้น ม้วนลำตัวขึ้นสั้น ๆ",
        "อย่าดึงคอ — มือแตะข้างหัวหรืออก",
        "เกร็งท้องตอนบนสุด 1 วินาที",
      ],
      defaultSets: 3,
      defaultReps: "12-20",
      startKg: null,
      restSec: 45,
    },
    plank: {
      id: "plank",
      name: "Plank",
      nameTh: "แพลงก์ค้าง",
      muscle: "แกนกลาง",
      equipment: "พื้น / บอล (advanced)",
      image: "assets/exercises/core.jpg",
      cues: [
        "ลำตัวเป็นเส้นตรงจากหัวถึงส้นเท้า",
        "อย่าให้สะโพกยุบหรือยกสูงเกิน",
        "หายใจสม่ำเสมอ เกร็งท้องและก้นเบา ๆ",
      ],
      defaultSets: 3,
      defaultReps: "30-45 วิ",
      startKg: null,
      restSec: 45,
      isTimed: true,
    },
    band_pull_apart: {
      id: "band_pull_apart",
      name: "Band Pull-Apart",
      nameTh: "ยางดึงแยกมือ (ท่าทาง)",
      muscle: "ไหล่หลัง · บนหลัง",
      equipment: "ยางยืด",
      image: "assets/exercises/band.jpg",
      cues: [
        "เหยียดแขนไปข้างหน้า ดึงยางแยกจนแตะอก",
        "สะบักบีบเข้า ควบคุมกลับ",
      ],
      defaultSets: 3,
      defaultReps: "15-25",
      startKg: null,
      bandLevel: "เบา",
      restSec: 45,
    },
    treadmill_walk: {
      id: "treadmill_walk",
      name: "Treadmill Walk",
      nameTh: "เดินลู่วิ่ง (ไม่ปรับ incline)",
      muscle: "คาร์ดิโอเบา · กู้ตัว",
      equipment: "ลู่วิ่ง",
      image: "assets/exercises/cardio.jpg",
      cues: [
        "เดินสบาย พูดคุยได้ — ไม่ใช่วิ่งหมดแรง",
        "ใช้เป็น finisher หรือวันพักแอคทีฟ",
        "หายใจจมูก+ปากตามสบาย ไหล่ผ่อนคลาย",
      ],
      defaultSets: 1,
      defaultReps: "10-20 นาที",
      startKg: null,
      restSec: 0,
      isCardio: true,
    },
    warmup_march: {
      id: "warmup_march",
      name: "Warm-up: Easy March / Arm Circles",
      nameTh: "วอร์มอัพ: เดินอยู่กับที่ + หมุนแขน",
      muscle: "ทั้งตัว",
      equipment: "—",
      image: "assets/exercises/cardio.jpg",
      cues: [
        "3–5 นาที ขยับข้อไหล่ สะโพก เข่า",
        "ค่อยเพิ่มระยะการเคลื่อนไหว อย่ารีบยกหนักทันที",
      ],
      defaultSets: 1,
      defaultReps: "3-5 นาที",
      startKg: null,
      restSec: 0,
      isWarmup: true,
    },
  },

  /* day templates: long (~60), full (~45+), short (~30)
   Rep ranges: compound 8-15 · isolation 12-20 (wide for ~4kg DB jumps) */
  days: [
    {
      id: "push",
      title: "Push — อก · ไหล่ · ไตร",
      titleEn: "Day 1 · Push",
      focus: "อก–ไหล่–ไตร · สร้างความกว้างช่วงบน (V-taper)",
      full: {
        minutes: 45,
        blocks: [
          { exerciseId: "warmup_march" },
          { exerciseId: "incline_db_press", sets: 4, reps: "8-15" },
          { exerciseId: "flat_db_press", sets: 3, reps: "8-15" },
          { exerciseId: "db_ohp", sets: 3, reps: "8-15" },
          { exerciseId: "lateral_raise", sets: 3, reps: "12-20" },
          { exerciseId: "db_kickback", sets: 3, reps: "12-20" },
          { exerciseId: "band_pushdown", sets: 2, reps: "12-20" },
        ],
      },
      short: {
        minutes: 30,
        blocks: [
          { exerciseId: "warmup_march" },
          { exerciseId: "incline_db_press", sets: 3, reps: "8-15" },
          { exerciseId: "db_ohp", sets: 3, reps: "8-15" },
          { exerciseId: "lateral_raise", sets: 3, reps: "12-20" },
          { exerciseId: "band_pushdown", sets: 2, reps: "12-20" },
        ],
      },
      long: {
        minutes: 60,
        blocks: [
          { exerciseId: "warmup_march" },
          { exerciseId: "incline_db_press", sets: 4, reps: "8-15" },
          { exerciseId: "flat_db_press", sets: 4, reps: "8-15" },
          { exerciseId: "db_ohp", sets: 4, reps: "8-15" },
          { exerciseId: "lateral_raise", sets: 4, reps: "12-20" },
          { exerciseId: "db_kickback", sets: 3, reps: "12-20" },
          { exerciseId: "band_pushdown", sets: 3, reps: "12-20" },
          { exerciseId: "plank", sets: 2, reps: "30-40 วิ" },
        ],
      },
    },
    {
      id: "pull",
      title: "Pull — หลัง · ไบ",
      titleEn: "Day 2 · Pull",
      focus: "หลังกว้าง + ไบ · โหนคุณภาพ 3–4 ครั้ง (กล้ามเนื้อขายังดีอยู่แล้ว — โฟกัสบน)",
      full: {
        minutes: 45,
        blocks: [
          { exerciseId: "warmup_march" },
          { exerciseId: "pullup", sets: 3, reps: "3-8" },
          { exerciseId: "band_assisted_pullup", sets: 2, reps: "6-12" },
          { exerciseId: "db_row", sets: 3, reps: "8-15" },
          { exerciseId: "rear_delt_fly", sets: 3, reps: "12-20" },
          { exerciseId: "db_curl", sets: 3, reps: "12-20" },
          { exerciseId: "band_face_pull", sets: 3, reps: "12-20" },
        ],
      },
      short: {
        minutes: 30,
        blocks: [
          { exerciseId: "warmup_march" },
          { exerciseId: "pullup", sets: 3, reps: "3-8" },
          { exerciseId: "db_row", sets: 3, reps: "8-15" },
          { exerciseId: "db_curl", sets: 3, reps: "12-20" },
          { exerciseId: "band_face_pull", sets: 2, reps: "12-20" },
        ],
      },
      long: {
        minutes: 60,
        blocks: [
          { exerciseId: "warmup_march" },
          { exerciseId: "pullup", sets: 4, reps: "3-8" },
          { exerciseId: "band_assisted_pullup", sets: 3, reps: "6-12" },
          { exerciseId: "db_row", sets: 4, reps: "8-15" },
          { exerciseId: "rear_delt_fly", sets: 3, reps: "12-20" },
          { exerciseId: "db_curl", sets: 4, reps: "12-20" },
          { exerciseId: "band_face_pull", sets: 3, reps: "12-20" },
          { exerciseId: "band_pull_apart", sets: 2, reps: "15-25" },
        ],
      },
    },
    {
      id: "legs",
      title: "Legs + Core",
      titleEn: "Day 3 · Legs & Core",
      focus: "ขาพอสมส่วน + core — ไม่ต้อง bulk ขาเพิ่มมาก (Fitdays: ขายังสูงอยู่)",
      full: {
        minutes: 45,
        blocks: [
          { exerciseId: "warmup_march" },
          { exerciseId: "db_squat", sets: 3, reps: "8-15" },
          { exerciseId: "db_rdl", sets: 3, reps: "8-15" },
          { exerciseId: "split_squat", sets: 3, reps: "8-15/ข้าง" },
          { exerciseId: "calf_raise", sets: 3, reps: "12-20" },
          { exerciseId: "ball_crunch", sets: 3, reps: "12-20" },
          { exerciseId: "plank", sets: 3, reps: "30-45 วิ" },
        ],
      },
      short: {
        minutes: 30,
        blocks: [
          { exerciseId: "warmup_march" },
          { exerciseId: "db_squat", sets: 3, reps: "8-15" },
          { exerciseId: "db_rdl", sets: 3, reps: "8-15" },
          { exerciseId: "ball_crunch", sets: 3, reps: "12-20" },
          { exerciseId: "plank", sets: 2, reps: "30-40 วิ" },
        ],
      },
      long: {
        minutes: 60,
        blocks: [
          { exerciseId: "warmup_march" },
          { exerciseId: "db_squat", sets: 4, reps: "8-15" },
          { exerciseId: "db_rdl", sets: 4, reps: "8-15" },
          { exerciseId: "split_squat", sets: 3, reps: "8-15/ข้าง" },
          { exerciseId: "calf_raise", sets: 4, reps: "12-20" },
          { exerciseId: "ball_crunch", sets: 3, reps: "12-20" },
          { exerciseId: "plank", sets: 3, reps: "40-50 วิ" },
          { exerciseId: "treadmill_walk", sets: 1, reps: "8-10 นาที" },
        ],
      },
    },
    {
      id: "upper",
      title: "Upper Aesthetic",
      titleEn: "Day 4 · Upper Aesthetic",
      focus: "เน้นรูปทรงอก–ไหล่–แขน",
      full: {
        minutes: 45,
        blocks: [
          { exerciseId: "warmup_march" },
          { exerciseId: "incline_db_press", sets: 3, reps: "8-15" },
          { exerciseId: "db_row", sets: 3, reps: "8-15" },
          { exerciseId: "lateral_raise", sets: 4, reps: "12-20" },
          { exerciseId: "db_ohp", sets: 2, reps: "8-15" },
          { exerciseId: "db_curl", sets: 3, reps: "12-20" },
          { exerciseId: "db_kickback", sets: 3, reps: "12-20" },
        ],
      },
      short: {
        minutes: 30,
        blocks: [
          { exerciseId: "warmup_march" },
          { exerciseId: "incline_db_press", sets: 3, reps: "8-15" },
          { exerciseId: "db_row", sets: 3, reps: "8-15" },
          { exerciseId: "lateral_raise", sets: 3, reps: "12-20" },
          { exerciseId: "db_curl", sets: 2, reps: "12-20" },
        ],
      },
      long: {
        minutes: 60,
        blocks: [
          { exerciseId: "warmup_march" },
          { exerciseId: "incline_db_press", sets: 4, reps: "8-15" },
          { exerciseId: "db_row", sets: 4, reps: "8-15" },
          { exerciseId: "lateral_raise", sets: 5, reps: "12-20" },
          { exerciseId: "db_ohp", sets: 3, reps: "8-15" },
          { exerciseId: "db_curl", sets: 4, reps: "12-20" },
          { exerciseId: "db_kickback", sets: 3, reps: "12-20" },
          { exerciseId: "band_face_pull", sets: 3, reps: "12-20" },
        ],
      },
    },
    {
      id: "pull2",
      title: "Pull + Posture",
      titleEn: "Day 5 · Pull & Posture",
      focus: "โหนต่อเนื่อง + ไหล่หลัง/ท่าทาง",
      full: {
        minutes: 45,
        blocks: [
          { exerciseId: "warmup_march" },
          { exerciseId: "pullup", sets: 3, reps: "3-8" },
          { exerciseId: "db_row", sets: 4, reps: "8-15" },
          { exerciseId: "band_face_pull", sets: 3, reps: "12-20" },
          { exerciseId: "rear_delt_fly", sets: 3, reps: "12-20" },
          { exerciseId: "band_pull_apart", sets: 3, reps: "15-25" },
          { exerciseId: "db_curl", sets: 2, reps: "12-20" },
        ],
      },
      short: {
        minutes: 30,
        blocks: [
          { exerciseId: "warmup_march" },
          { exerciseId: "pullup", sets: 3, reps: "3-8" },
          { exerciseId: "db_row", sets: 3, reps: "8-15" },
          { exerciseId: "band_face_pull", sets: 3, reps: "12-20" },
          { exerciseId: "band_pull_apart", sets: 2, reps: "15-25" },
        ],
      },
      long: {
        minutes: 60,
        blocks: [
          { exerciseId: "warmup_march" },
          { exerciseId: "pullup", sets: 4, reps: "3-8" },
          { exerciseId: "band_assisted_pullup", sets: 2, reps: "6-12" },
          { exerciseId: "db_row", sets: 4, reps: "8-15" },
          { exerciseId: "band_face_pull", sets: 4, reps: "12-20" },
          { exerciseId: "rear_delt_fly", sets: 3, reps: "12-20" },
          { exerciseId: "band_pull_apart", sets: 3, reps: "15-25" },
          { exerciseId: "db_curl", sets: 3, reps: "12-20" },
        ],
      },
    },
    {
      id: "full",
      title: "Full Body + Walk",
      titleEn: "Day 6 · Full Body",
      focus: "compound ทั้งตัว + เดินลู่วิ่งเบา",
      full: {
        minutes: 50,
        blocks: [
          { exerciseId: "warmup_march" },
          { exerciseId: "flat_db_press", sets: 3, reps: "8-15" },
          { exerciseId: "db_row", sets: 3, reps: "8-15" },
          { exerciseId: "db_squat", sets: 3, reps: "8-15" },
          { exerciseId: "db_ohp", sets: 2, reps: "8-15" },
          { exerciseId: "plank", sets: 2, reps: "30-40 วิ" },
          { exerciseId: "treadmill_walk", sets: 1, reps: "12-15 นาที" },
        ],
      },
      short: {
        minutes: 30,
        blocks: [
          { exerciseId: "warmup_march" },
          { exerciseId: "flat_db_press", sets: 3, reps: "8-15" },
          { exerciseId: "db_row", sets: 3, reps: "8-15" },
          { exerciseId: "db_squat", sets: 2, reps: "8-15" },
          { exerciseId: "treadmill_walk", sets: 1, reps: "8-10 นาที" },
        ],
      },
      long: {
        minutes: 60,
        blocks: [
          { exerciseId: "warmup_march" },
          { exerciseId: "flat_db_press", sets: 4, reps: "8-15" },
          { exerciseId: "db_row", sets: 4, reps: "8-15" },
          { exerciseId: "db_squat", sets: 3, reps: "8-15" },
          { exerciseId: "db_ohp", sets: 3, reps: "8-15" },
          { exerciseId: "lateral_raise", sets: 3, reps: "12-20" },
          { exerciseId: "plank", sets: 3, reps: "30-40 วิ" },
          { exerciseId: "treadmill_walk", sets: 1, reps: "12-15 นาที" },
        ],
      },
    },
    {
      id: "rest",
      title: "Rest / Active Recovery",
      titleEn: "Day 7 · Rest",
      focus: "พัก หรือเดินเบา — กู้กล้ามเนื้อ",
      isRest: true,
      full: {
        minutes: 20,
        blocks: [{ exerciseId: "treadmill_walk", sets: 1, reps: "15-25 นาที" }],
      },
      short: {
        minutes: 15,
        blocks: [{ exerciseId: "treadmill_walk", sets: 1, reps: "10-15 นาที" }],
      },
      long: {
        minutes: 30,
        blocks: [{ exerciseId: "treadmill_walk", sets: 1, reps: "25-30 นาที" }],
      },
    },
  ],
};
